### PR TITLE
RAS-914 Migrate Mock eq v2 from management to CI project

### PR DESCRIPTION
**Pull request by arroyoAle**
(Card description written by anwilkie)

# What and why?
The image for this repo needed to start being pushed to the `ons-ci-rmrasbs` project instead of the `ons-rasrmbs-management`. This PR makes that changes, as well as a slight edit to the Github Actions build file to ensure that the image is being built with the correct project. Previously, the `$GOOGLE_PROJECT_ID` secret was used when building the image, which was fine when this corresponds to the management project, and was also being used for `$RELEASE_PROJECT`. However, now that these two secrets have different values, the variable calls had to be updated to use the $RELEASE_PROJECT` secret when building the image.

# How to test?
Deploy and test the service. Also, look at [here](https://console.cloud.google.com/artifacts/docker/ons-ci-rmrasbs/europe-west2/images/mock-eq?project=ons-ci-rmrasbs) and verify that the image has been built in the CI project.

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-914)

### CODE REVIEW

**Review by SteveScorfield — APPROVED** [review]
Looks good to me and deploys fine

**Review by matthew-robinson-ons — CHANGES_REQUESTED** [review]
The comment.yml actions are failing so /deploy is not working at the moment. I don't think it's related to this PR but we should fix it moving forward.

**Comment by SteveScorfield** [comment]
This should work once merged. However, in order to test, deploy to your dev env, goto the yaml in GCP of the service and edit the image under spec and replace 'ons-rasrmbs-management' with 'ons-ci-rmrasbs' and update it to pr-35 (if required). This is roughly line 245. We need to double check this works correctly when merged.

**Comment by matthew-robinson-ons** [comment]
This works when tested without /deploy. Agree we need to raise a PR after merging and check the comment.yaml works and raise a card if it is still broken.

**Review by matthew-robinson-ons — APPROVED** [review]

**Pull request merged**
